### ISSUE TITLE
TContextMenu class not found

### ISSUE THREAD

**Issue by rcontractor** [zerodivisi0n/FinderMenu#2]
I see that there is a Finder_symbols.txt which contains TContextMenu. How do I incorporate that into the project to be used? Do I need to convert it to a .h file and then include that in my .m?
I am trying to use the FinderMenu project within my own project to add a context menu.

Even if I do put TContextMenu interface in a header file, it still fails at objc_getClass("TContextMenu") as an unknown class/nil.

**Comment by zerodivisi0n** [comment]
Сan you describe your actions in more detail? In which place did you call objc_getClass("TContextMenu")?

On which version of OS X is it happening? I tested my solution only on the latest version - 10.8.

**Comment by rcontractor** [comment]
Using OSX 10.7.4, Xcode 4.5.2.
I have a project. Within that project is FinderExt directory, exactly as you have it. Inside of Products is FinderExt.bundle. When the app starts running, it runs FinderExt.m and runs OverrideClass, which calls objc_getClass("TContextMenu").

```
// Create helper object
gNodeHelper = [[TFENodeHelper alloc] init];
if (gNodeHelper == nil) {
    NSLog(@"Failed to instantiate 'TFENodeHelper' class");
    return;
}

Method method = class_getInstanceMethod(self, @selector(override_configureWithNodes:browserController:container:));
OverrideClass("TContextMenu", @selector(configureWithNodes:browserController:container:), method);
```

static void OverrideClass(const char *name, SEL origSEL, Method overrideMethod) {
  Class c = objc_getClass(name);
    if (c != nil) {
        //do stuff
   } else {
        NSLog(@"Class %s not found to override", name);
    }
}

I get "Class TContextMenu not found to override".

This first part instantiating TFENodeHelper class also fails in TFENodeHelper.m, the conditions below are not met so _pathMethodType does not get set.

if (class_getInstanceMethod(_class, @selector(fullPath))) {
       _pathMethodType = TFENodePathMethodTypeFullPath;
} else if (class_getInstanceMethod(_class, @selector(previewItemURL))) {
        _pathMethodType = TFENodePathMethodTypePreviewItemURL;
}

I have commented it out for now and set _pathMethodType = TFENodePathMethodTypeFullPath, but not really sure what that means.

**Comment by zerodivisi0n** [comment]
`FinderExt.bundle` first must be injected into Finder process. And code from `FinderExt.m` should be running inside a Finder process. To do so you need a helper _loader_ application. Loader uses `mach_inject` to inject code into arbitrary process and should run with root privileges. In my example code I guess that user will run it as root. But this method is not suitable for real applications. In this case, it's necessary to create a separate _loader_ tool. It must use the SUID-bit or other privilege-escalation technique.

Problem with `TFENodeHelper` also occurs for the same reason - running not inside Finder process.

**Comment by rcontractor** [comment]
Ok. I have the mach_inject code in there, but it is getting run after the FinderExt.m runs. I assume this is incorrect then. I guess somehow it is not loading into the Finder process, though I tried to mirror your project structure. Let me see what is going wrong. So my FinderExt.m should not run first correct? It should only run when the mach_inject bundle is called?

**Comment by rcontractor** [comment]
I figured out why that was happening, then I ran as root and got "Inject successful." Can you send me a picture of what I should expect to see? I thought I should see a context menu in the finder if I right click on a file. I don't see that.

**Comment by faisyl** [comment]
Another way of loading the bundle - atleast for development is to use 
SIMBL to do the injection for you.

rcontractor wrote:

**Comment by rcontractor** [comment]
Is there a good example of how to use SIMBL? My sole aim is to insert a context menu with submenu option for my app (only within a specific Finder folder).

**Comment by faisyl** [comment]
This is a good starting point

http://stackoverflow.com/questions/1294335/how-to-write-os-x-finder-plugin

rcontractor wrote:

**Comment by rcontractor** [comment]
I think I don't see the context menu because EventLoopTimerEntry is not getting called, thus load_bundle_package is not getting called. I don't see any log prints from the FinderExt. Maybe something is wrong with my mach_inject (looks like the wrong framework is loading, though I can't figure out why). Please attach a picture of what I should see in the context menu after a successful run. Thanks.

**Comment by rcontractor** [comment]
Also, any other idea why EventLoopTimerEntry won't run? Or how to see what my framework is doing?

**Comment by rcontractor** [comment]
My framework was not updated in /Library/Frameworks. I got the bundle to load. Just not seeing the new context menu now when I right click on a file in Finder. Am I missing a step?

**Comment by zerodivisi0n** [comment]
I don't use SIMBL because with it is difficult to make an application to the end user. And not every user agrees to install an additional dependency with the application. Applications like Dropbox or Google Drive use their own methods to load bundle into Finder.

So I can't help you with SIMPL because I simply do not use it.

> I figured out why that was happening, then I ran as root and got "Inject successful." Can you send me a picture of what I should expect to see? I thought I should see a context menu in the finder if I right click on a file. I don't see that.

Current implementation does not work in Icon View mode and not tested anywhere except OS X 10.8. So in your case, it may simply not work. I want to create a universal solution that will work on all versions of OS X, starting from 10.6. But as long as it is in active development and any feedback is important to me.

I still can not show a screenshot of the real application in which I use this method. It's not production-ready product yet. But for example, here's a screenshot of FinderMenu project: ![Screenshot](https://dl.dropbox.com/u/967653/FinderMenu.png)

**Comment by rcontractor** [comment]
I have tried viewing in List and Columns View, and it doesn't show up.
I do get these messages though:

Main bundle: com.apple.finder
Finder[1992]: orig=0x7f8217b26a58, override=0x7f8217bb87f8
Finder[1992]: Method 'menuForEvent:' overriden in class TContextMenu
Finder[1992]: FinderExt load is complete

I don't think there should be a big difference between 10.7.4 and 10.8. Where did you get the configureWithNodes:browserController:container: method from? Along with the other TContextMenu methods? I tried to google those in case I needed to change something there, but there is no info. This project is the first thing that shows up in my google search.

**Comment by rcontractor** [comment]
I wonder if there is a different method other that 'menuForEvent' that I need to change. I can't find much info on that method either.

**Comment by rcontractor** [comment]
It may be helpful to mention that I am using this code with a pyobjc project. Would that have any affect on the result?

**Comment by rcontractor** [comment]
Also, is there a way to undo the changes?

**Comment by zerodivisi0n** [comment]
It seems that there are still differences between 10.7 and 10.8. You can obtain Finder symbols from your version of Finder using [class_dump](http://stevenygard.com/projects/class-dump/) tool. Then send them to me and I'll try to understand what was happening.

> It may be helpful to mention that I am using this code with a pyobjc project. Would that have any affect on the result?

If you see the message _Finder[1992]: FinderExt load is complete_ it does not matter how the code is executed. Code is injected into Finder and required method overridden.

> Also, is there a way to undo the changes?

The only way I know is to kill Finder and then it will be automatically restarted. Run this command into Terminal:
`killall Finder`. Can you try to repeat injection after restart? Code does not update after the second injection, therefore you can not see the menu.

**Comment by rcontractor** [comment]
In 10.7.4, this is different:
- (void)configureWithNodes:(const struct TFENodeVector *)arg1 windowController:(id)arg2 container:(BOOL)arg3;

In 10.8, it is:
- (void)configureWithNodes:(const struct TFENodeVector *)arg1 browserController:(id)arg2 container:(BOOL)arg3;

Changing it from browserController to windowController did the trick. I can now see the menu. Thanks!!! Now to make it work in 10.6, 10.7, and 10.8...

**Comment by zerodivisi0n** [comment]
Great! Good work!

But in Icon View mode it still not working?

**Comment by rcontractor** [comment]
Thanks for the help! Correct, in Icon View mode, it still does not work.

**Comment by zerodivisi0n** [comment]
Today I finished the implementation with Icon View support.
