### ISSUE TITLE
Building Instructions

### ISSUE THREAD

**Issue by wprater** [zerodivisi0n/FinderMenu#3]
Can you elaborate on the build instructions?  I've pulled in the submodules, used `xcodebuild` but it's getting link errors still.  Maybe Im missing something obvious?

**Comment by zerodivisi0n** [comment]
There is need to change the settings in the submodule project, this can be cause of linking errors.
I'm going to update the implementation for a week. Most likely I'll exclude submodules and add code directly to the project. So, keep in touch!

**Comment by wprater** [comment]
Curious as to the progress on this?  Any info you can point me to change the settings?

**Comment by zerodivisi0n** [comment]
I apologize that did not keep my promises. Today I found a little bit of time to update the project. Now it's building without errors out of box. But this is an old implementation that does not support Icon View and works only on Mac OS X 10.8. I plan to finish the new implementation to the end of the week. And while you can check can you compile this version.

**Comment by zerodivisi0n** [comment]
I finally found the time to update the project. Now it supports Icon View and should work with all OS X versions since 10.6.
